# Content-Based Recommendation System Notebook
In this notebook, we will explore and implement a content-based recommendation system. Content-based recommendation systems suggest items to users based on the characteristics of the items and a profile of the user's preferences.
This approach is particularly useful when we have a lot of information about the items and the users' preferences. We will build a simple content-based recommendation system using Python and the scikit-learn library.

## Table of Contents

1- Introduction
    What is a Content-Based Recommendation System?
    How Does it Work?
    Data Preparation
2- Dataset
    Feature Extraction
    Data Preprocessing
    Building the Content-Based Recommendation System
3- TF-IDF
    Vectorization
    Cosine Similarity
    Recommending Items
4- Evaluation
    Evaluation Metrics
5- Conclusion
## - Summary
## 1. Introduction
 - What is a Content-Based Recommendation System?
    A content-based recommendation system recommends items to users based on the content or characteristics of the items. This type of recommendation system focuses on    understanding the properties of items and learning user preferences from the items they have interacted with in	 the past.
 - How Does it Work?
   The working principle of a content-based recommendation system can be summarized in a few steps:
        1- Feature Extraction: Extract relevant features from the items. For example, in a movie recommendation system, features could include genre, director, actors, and plot keywords.

        2- User Profile: Create a user profile based on their interactions with items. This profile is essentially a summary of the features of items the user has liked or interacted with in the past.

        3- Recommendation: Calculate the similarity between the user profile and each item's features. Items that are most similar to the user profile are recommended.

## 2. Data Preparation
Dataset
- We will use a dataset containing movie information, including titles, genres, and descriptions.

In [33]:
# Import needed modules
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
import re

In [3]:
# Read data
df = pd.read_csv("E:\\NLP\\movies.csv")

In [4]:
df.shape

(4803, 24)

In [5]:
# printing the first 2 rows of the dataframe
df.head(2)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski

In [6]:
# Get data information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 4803 non-null   int64
 1   budget                4803 non-null   int64
 2   genres                4775 non-null   object
 3   homepage              1712 non-null   object
 4   id                    4803 non-null   int64
 5   keywords              4391 non-null   object
 6   original_language     4803 non-null   object
 7   original_title        4803 non-null   object
 8   overview              4800 non-null   object
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object
 11  production_countries  4803 non-null   object
 12  release_date          4802 non-null   object
 13  revenue               4803 non-null   int64
 14  runtime               4801 non-null   float64
 15  spoken_languages      4803 non-null   object
 16  status                4803 non-null   object
 17  tagline               3959 non-null   object
 18  title                 4803 non-null   object
 19  vote_average          4803 non-null   float64
 20  vote_count            4803 non-null   int64
 21  cast                  4760 non-null   object
 22  crew                  4803 non-null   object
 23  director              4773 non-null   object
dtypes: float64(3), int64(5), object(16)
memory usage: 900.7+ KB

In [7]:
# Selecting the relevant features for recommendation
selected_features  = ["genres" , "keywords" , 'overview' , "title"]

df = df[selected_features]

In [8]:
df.shape

(4803, 4)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genres    4775 non-null   object
 1   keywords  4391 non-null   object
 2   overview  4800 non-null   object
 3   title     4803 non-null   object
dtypes: object(4)
memory usage: 150.2+ KB

In [10]:
df = df.dropna().reset_index(drop=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4387 entries, 0 to 4386
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genres    4387 non-null   object
 1   keywords  4387 non-null   object
 2   overview  4387 non-null   object
 3   title     4387 non-null   object
dtypes: object(4)
memory usage: 137.2+ KB

In [12]:
# combining all the 5 selected features
df["combined"] = df["genres"] + " " + df["keywords"] + " " + df["overview"] + " " + df["title"]

In [13]:
df.head(2)

,genres,keywords,overview,title,combined
0,Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,"In the 22nd century, a paraplegic Marine is di...",Avatar,Action Adventure Fantasy Science Fiction cultu...
1,Adventure Fantasy Action,ocean drug abuse exotic island east india trad...,"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,Adventure Fantasy Action ocean drug abuse exot...

In [14]:
data = df[["title" , "combined"]]

In [15]:
data.head(2)

,title,combined
0,Avatar,Action Adventure Fantasy Science Fiction cultu...
1,Pirates of the Caribbean: At World's End,Adventure Fantasy Action ocean drug abuse exot...

In [34]:
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

In [ ]:
def preprocess_text(text):
    # Remove special characters and numbers
    text = re.sub(r"[^a-zA-Z\s]" , " " , text)
    text = text.lower()
    # Convert to lowercase
    tokens = word_tokenize(text)
    # Tokenize and remove stopwords
    tokens = [word for word in tokens if word not in stop_words]

    tokens = [stemmer.stem(word) for word in tokens if word not in stop_words]
    return " ".join(tokens)

In [18]:
data["clean_text"] = data["combined"].apply(preprocess_text)

C:\Users\Talaat Mostafa\AppData\Local\Temp\ipykernel_12928\212055494.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["clean_text"] = data["combined"].apply(preprocess_text)

In [19]:
# converting the text data to feature vectors
tfidf_vectorizer = TfidfVectorizer(max_features = 5000, ngram_range=(1,2))
tfidf_matrix = tfidf_vectorizer.fit_transform(data["clean_text"])

In [20]:
# getting the similarity scores using cosine similarity
cosine_sim = cosine_similarity(tfidf_matrix)

In [21]:
print(cosine_sim)

[[1.         0.04441165 0.02539097 ... 0.00335349 0.         0.        ]
 [0.04441165 1.         0.02317264 ... 0.0132465  0.02586368 0.00567565]
 [0.02539097 0.02317264 1.         ... 0.00758224 0.0130973  0.        ]
 ...
 [0.00335349 0.0132465  0.00758224 ... 1.         0.         0.        ]
 [0.         0.02586368 0.0130973  ... 0.         1.         0.04971783]
 [0.         0.00567565 0.         ... 0.         0.04971783 1.        ]]

In [22]:
# creating a list with all the movie names given in the dataset
list_of_movies = data["title"].tolist()

In [23]:
# getting the movie name from the user
#movie_name = input(' Enter your favourite movie name : ')
movie_name = "Iron Man"

In [24]:
# finding the close match for the movie name given by the user
find_close_movie = difflib.get_close_matches(movie_name , list_of_movies)
print(find_close_movie)  # printing the closest match

['Iron Man', 'Iron Man 3', 'Iron Man 2']

In [25]:
index_of_movie = data[data.title == find_close_movie[0]].index[0]
index_of_movie

68

In [26]:
# getting a list of similar movies
similarity_score = list(enumerate(cosine_sim[index_of_movie]))
#similarity_score

In [27]:
# sorting the movies based on their similarity score
sort_similar_movies = sorted(similarity_score , key = lambda x:x[1] , reverse = True)
print(sort_similar_movies)

[(68, 1.0), (78, 0.45365107541692595), (31, 0.37711572930814113), (7, 0.26982710977283825), (506, 0.2632566436566824), (99, 0.23546516195064715), (201, 0.2216124554549362), (180, 0.21927322074385389), (64, 0.2085862197576598), (92, 0.20544377159609653), (16, 0.20238909046512488), (172, 0.1942485267235821), (1118, 0.18932121783021066), (230, 0.1860700998940901), (26, 0.18398455990436766), (33, 0.1827148414459646), (3223, 0.16281470338846885), (781, 0.1623227477054796), (75, 0.1581543229983762), (2165, 0.1548972788750477), (1705, 0.14944062372965636), (120, 0.14537002995088827), (124, 0.14338169149318528), (2159, 0.1425058688496826), (46, 0.14184725682652916), (3200, 0.14128170740702417), (935, 0.13395952209067155), (548, 0.13310801740839065), (1827, 0.1305935915721117), (240, 0.12663587357992967), (4022, 0.12146750541388694), (30, 0.1197285352461907), (1055, 0.11630152099632465), (3782, 0.11618096756491872), (2359, 0.11523549569540116), (137, 0.11507920043399306), (416, 0.11461514625987829), (3452, 0.11338985080626088), (2983, 0.10748166875634377), (358, 0.10738382307220322), (1401, 0.10647715211318816), (3843, 0.10628764901654505), (1063, 0.10492909497737027), (2313, 0.102191948946702), (1911, 0.1020240443488728), (4091, 0.10118744230152672), (1596, 0.10039574717445222), (167, 0.10032651448934847), (2786, 0.09977490465063839), (3438, 0.0986449367599486), (83, 0.09854922445094665), (14, 0.09803322111791203), (930, 0.09559143953021913), (1432, 0.09488425548697335), (2537, 0.0942132340186243), (38, 0.09261514042664501), (218, 0.09221185063439273), (10, 0.09182951097522275), (1030, 0.09159613136252226), (206, 0.09053238945485213), (2906, 0.09017345709408203), (231, 0.08807359881134957), (4041, 0.08741167982685631), (1184, 0.08701612290796754), (1266, 0.08547088758863769), (2187, 0.08525840609595695), (721, 0.08486001422992907), (1613, 0.08419340391369398), (595, 0.08408851878770207), (1314, 0.08392412176742897), (1488, 0.08318907161872922), (1576, 0.08275767066225904), (798, 0.08212345330784031), (125, 0.08204630038867006), (2867, 0.08140905879292283), (3396, 0.08084210413946397), (52, 0.08060109058632392), (198, 0.08023175937197774), (485, 0.07959841947200955), (226, 0.07947013407341098), (1620, 0.07911021737486247), (390, 0.07873328551354444), (482, 0.07854721779961979), (194, 0.0785222314627511), (305, 0.0784485087030053), (534, 0.07835120017249271), (1160, 0.07814665690469355), (1685, 0.077793125238677), (0, 0.07743218109738696), (861, 0.07688094253943256), (1763, 0.07624057322825961), (3647, 0.07557499553898211), (363, 0.0754191362516115), (39, 0.07513199450474663), (3742, 0.07488904203774006), (127, 0.07485978226688562), (533, 0.0742018088521266), (725, 0.07343431752347604), (461, 0.07315996277097554), (1249, 0.07313202413160347), (4019, 0.07301212744048804), (396, 0.07262464739022607), (1213, 0.07251226977962974), (117, 0.07208127859834855), (20, 0.07203676631305224), (471, 0.07193160458261133), (1788, 0.0716262007701507), (3561, 0.07154458175379032), (989, 0.071427739437463), (1991, 0.07083231536840597), (3735, 0.0707561904173001), (3762, 0.07061592939320857), (1136, 0.07060092530082095), (582, 0.06974433614682785), (3686, 0.06925746443922931), (3675, 0.0687146431555602), (771, 0.06859727486486478), (2677, 0.06857323448660843), (2247, 0.06851073224050384), (3911, 0.06800799997713083), (2265, 0.06787585499533307), (775, 0.06777225305570765), (565, 0.0677543509761505), (3722, 0.0676173728960075), (4289, 0.06758367585847384), (411, 0.06736288201363204), (2635, 0.06731507891866018), (946, 0.06710172407842767), (4087, 0.06675586072463849), (1680, 0.06648444882978921), (164, 0.0664591123813963), (252, 0.06645719264124318), (255, 0.06594362202819846), (668, 0.06583555450360888), (73, 0.06565464702951691), (2096, 0.06554105025666247), (163, 0.0652140653694817), (1341, 0.06466899843258302), (540, 0.06450429145241461), (965, 0.06446130434265125), (1891, 0.06432835664127103), (1368, 0.06423848304087668), (2615, 0.06411668819334174), (654, 0.06376393776251638), (1015, 0.06373748936161282), (490, 0.0634573663689044), (3916, 0.0633366252346003), (1994, 0.06324227163450903), (890, 0.06299212322737952), (2351, 0.06290237485118128), (236, 0.06263900911095853), (247, 0.0618708833716447), (269, 0.06176280228247592), (2183, 0.06150453378563478), (276, 0.061499150122710754), (51, 0.061234626924353816), (847, 0.060692507955506646), (1251, 0.06058469980470231), (1810, 0.060493115714814555), (1941, 0.06011740567789985), (436, 0.06002451194159408), (1011, 0.06000719799873044), (2297, 0.05986065766971401), (147, 0.05985825338515316), (4294, 0.059845829708051024), (3006, 0.05975514709343977), (418, 0.05937913292022324), (1263, 0.059297652146328546), (2253, 0.059289481144271426), (1501, 0.059184163801823265), (264, 0.05842731411466876), (628, 0.05831674812540534), (728, 0.0577009175996137), (4376, 0.05719711025386197), (1084, 0.05684162112951263), (2509, 0.05660035013246867), (221, 0.05653796488597573), (655, 0.056396793848152604), (776, 0.05637062363312966), (445, 0.05636672234588878), (2709, 0.056259533028962035), (475, 0.05615889322935702), (1175, 0.05593446750659683), (368, 0.05558711360150023), (279, 0.0554681053759176), (601, 0.055431145270864415), (464, 0.05533507593130975), (2053, 0.05527297044643565), (696, 0.05500305656562056), (61, 0.05491615575683666), (222, 0.054835738919709165), (3966, 0.054831153179644335), (3171, 0.054781637458199924), (2735, 0.054761825888169566), (3813, 0.0547525985720173), (833, 0.05462875221873145), (1363, 0.05448045577178613), (3030, 0.054353983400965984), (3116, 0.05389869433132377), (503, 0.05386728853849763), (4357, 0.05381272237321233), (1720, 0.05377134823770459), (2261, 0.053670210678018734), (4383, 0.05360686814746399), (415, 0.0536030738383173), (3008, 0.05351055735001224), (41, 0.05348051960279184), (667, 0.05337830001226799), (3504, 0.053282747484058014), (995, 0.053180672501953824), (669, 0.05312020086145648), (4272, 0.053057327257388556), (2008, 0.052932021904312745), (1353, 0.05258224503260585), (329, 0.0525083749321377), (806, 0.05247924803358945), (3781, 0.05242146076559758), (3812, 0.052266095847474194), (1747, 0.05213468358549616), (109, 0.052048223331358084), (406, 0.052040311333131445), (3512, 0.051677573489700764), (1094, 0.051626715760965766), (161, 0.05157857684153699), (769, 0.05152559288899933), (1122, 0.05147056199963214), (3914, 0.051418166009190074), (1783, 0.0511204869481578), (2417, 0.05096207140191021), (2251, 0.05092814348287263), (1093, 0.0508854628627029), (2645, 0.05074916126935288), (3296, 0.05071634682098579), (1618, 0.05063217086014164), (1993, 0.050355133688064546), (2945, 0.05027568391106052), (3424, 0.050206027705116514), (1326, 0.0500601173434662), (360, 0.050043345231121326), (4096, 0.049968967863831565), (1048, 0.049943182300400055), (929, 0.04977164646171141), (2860, 0.04972205011525647), (4261, 0.04962352650603755), (3051, 0.049458727180458364), (254, 0.049421307220467406), (3983, 0.04923753878699977), (1332, 0.049202605651804315), (2438, 0.04908115716530174), (1197, 0.04907608184354967), (1956, 0.04901015421613737), (227, 0.04893701449101987), (4345, 0.04888027730623429), (232, 0.04871911008635695), (331, 0.0484455625063024), (1240, 0.04833696099648014), (2836, 0.04821950607099756), (3690, 0.04809819761094627), (1748, 0.0480712511923522), (3826, 0.048053044638893525), (2614, 0.04802513511894385), (2705, 0.048019191382259005), (3943, 0.048010719284481945), (1429, 0.04797251473511761), (359, 0.047876925999051606), (3066, 0.047857216473438026), (362, 0.047629741772791875), (1073, 0.047627564928791596), (9, 0.04735003830733565), (3418, 0.04732215060253521), (577, 0.04724034008427795), (648, 0.04684356835617089), (3788, 0.046813919992855724), (2667, 0.046783733326839834), (1787, 0.046686054462609275), (1948, 0.046667610551740235), (2866, 0.0462658286214102), (4288, 0.04615074321039685), (336, 0.046090736014952255), (4154, 0.045977298288249084), (2219, 0.04597099068494092), (2304, 0.045935073556275886), (4302, 0.04587836229189704), (3755, 0.045851392984451844), (620, 0.045756351093087816), (121, 0.045714938382165324), (1315, 0.04546099002838552), (3695, 0.04546053552297843), (341, 0.04543508036487627), (1914, 0.04540331131516414), (500, 0.0453936747175771), (146, 0.045372325170719215), (2835, 0.04519440217428782), (35, 0.045136453686252256), (2886, 0.04511399268700879), (3773, 0.04498310790325033), (258, 0.04479728480078096), (1279, 0.04471244480343939), (1398, 0.04470897834233304), (422, 0.04463323493862227), (2069, 0.044608778066623514), (468, 0.04453156316046094), (2355, 0.04452354344286787), (792, 0.04444372922884831), (1174, 0.044419267661055764), (1725, 0.04441891075962454), (43, 0.044418867674038076), (204, 0.04440209408500391), (2586, 0.044333973912345406), (1461, 0.044270381943597975), (941, 0.04422344561787883), (1745, 0.04421482825819842), (3627, 0.043936560686287825), (912, 0.04389311531075076), (2022, 0.04382658563316437), (365, 0.043788077551275145), (260, 0.0437645134001139), (478, 0.043760125726270346), (3454, 0.043733448247251644), (2652, 0.0436578655945739), (3361, 0.04361893946980667), (2348, 0.04353460605994937), (4275, 0.04344520809402253), (237, 0.04329084795278786), (1580, 0.04321436981981886), (2557, 0.04314750889623907), (4220, 0.04309083807148336), (498, 0.04300315671974485), (1440, 0.042875242998238944), (94, 0.0427691194111023), (1077, 0.04273612322674718), (3922, 0.042724481689952784), (3480, 0.042707593159712925), (651, 0.04264840565169102), (2542, 0.042564511042257634), (3666, 0.04253432688991661), (27, 0.042522940696658), (19, 0.042483175074222425), (2640, 0.04224473059720285), (320, 0.042183461525680546), (339, 0.0421292869937553), (1016, 0.04209739607332778), (1893, 0.04208601738290184), (317, 0.0418839527311916), (1183, 0.041800277967235545), (3650, 0.04174969439085847), (4226, 0.04164855064254714), (2649, 0.04160268623948148), (1601, 0.04155310266325226), (298, 0.04130939716511972), (79, 0.04129067900225444), (1579, 0.041162582512277786), (2068, 0.041105902817523354), (1769, 0.04106286934029), (591, 0.041049327528460175), (1789, 0.041029210317030204), (576, 0.040680997946164324), (4107, 0.04066268841516902), (56, 0.04059327892554678), (3122, 0.04051306301118435), (1782, 0.04044984429988027), (1192, 0.0403879998443523), (1138, 0.040343480377103835), (327, 0.0401670065320152), (3201, 0.04014833887478817), (2717, 0.04014494032240846), (3625, 0.04005597927666392), (834, 0.03995763993879973), (1407, 0.03993930672496554), (444, 0.03984024087668484), (344, 0.03976320011750586), (1585, 0.03969694659358565), (3168, 0.03960240334886829), (910, 0.03955751505510319), (1270, 0.039397696375959065), (156, 0.039195859049093146), (4253, 0.03911912879612058), (3415, 0.03900929137110354), (592, 0.03899886319519377), (1557, 0.038992786467943776), (4208, 0.038952411484388), (2576, 0.038760519054130936), (3817, 0.038729824402574706), (2774, 0.03866651832597763), (1764, 0.03865640527282706), (3397, 0.0386449129491609), (1466, 0.03863295086505032), (843, 0.03858524930490015), (3771, 0.03855431765658976), (2992, 0.03849865307945232), (2833, 0.038485482263814236), (2361, 0.03846881110098212), (350, 0.03839762487243372), (2300, 0.03839408859565959), (1551, 0.03837014472678878), (2044, 0.03833685197739885), (349, 0.03829532959166312), (1, 0.038275750423792575), (716, 0.038267195421859065), (196, 0.03814518000156157), (1007, 0.038132413088219116), (1605, 0.03810862646280284), (239, 0.03808522780566937), (1150, 0.038079495037144306), (3330, 0.03806751664796826), (1823, 0.037985707217597205), (337, 0.0379546555837116), (777, 0.037917120332165016), (2547, 0.03790155262321972), (3956, 0.037896732537424045), (1803, 0.03781300648841954), (228, 0.03781110877169967), (273, 0.037801202557911584), (2459, 0.03771162885513661), (761, 0.03760562542419242), (3611, 0.037598185169243264), (1335, 0.03750336871133713), (960, 0.03744394059008813), (2402, 0.03742786417070861), (398, 0.037424916846418334), (2034, 0.03734677315361816), (1067, 0.03731913716263123), (3127, 0.037259874329747374), (4092, 0.03725086131766183), (3901, 0.03723233079426589), (4052, 0.03722336807159774), (89, 0.03709980062429928), (1181, 0.03709000540780411), (4024, 0.037061770667929754), (1714, 0.03691614828575275), (1382, 0.036915068843523025), (2672, 0.03687875364561862), (181, 0.036865538010016824), (4232, 0.036707317088397744), (1888, 0.03660590174870595), (2442, 0.03658576473415192), (456, 0.03657078154339073), (205, 0.03644635621663706), (3003, 0.03635611427144418), (596, 0.036353791618008134), (2312, 0.03630135776788765), (2499, 0.0362945937691249), (1388, 0.03629356065971495), (3278, 0.036269743049836434), (1321, 0.03626161877164534), (4207, 0.036215344857880485), (158, 0.036197488435966284), (963, 0.036177118097985274), (546, 0.036167363304063484), (532, 0.036164865842815905), (1593, 0.03613722490689353), (1272, 0.03608597095366156), (3976, 0.036082961787997664), (2104, 0.03607935349162787), (47, 0.035996955903378425), (950, 0.035989220343155694), (114, 0.03596429705861894), (486, 0.03595688467519423), (4093, 0.035913869039510465), (210, 0.0358611147928641), (2013, 0.0358049518711838), (3243, 0.03577943807720109), (2757, 0.03576135010539842), (2666, 0.03570112937373803), (326, 0.03564634198081487), (796, 0.03554773133993989), (355, 0.035475045220241974), (113, 0.03541014750681897), (656, 0.035403135616090035), (2520, 0.03540280935563621), (2541, 0.0352644048929787), (2373, 0.03521295485841707), (4064, 0.0351941853815802), (3143, 0.03518775525000731), (2409, 0.03518251192194636), (559, 0.035084399948015904), (3414, 0.035021226307816414), (1478, 0.035009344556935613), (1191, 0.034984870418449554), (1508, 0.03492951602874163), (921, 0.034886445151542905), (711, 0.034853995501032194), (1424, 0.03484109700747176), (28, 0.03475865799290343), (4331, 0.03466669107069985), (3984, 0.03463216902510297), (106, 0.03456521090215392), (737, 0.03448383601881986), (3064, 0.03447615496975834), (4088, 0.03445724200044969), (3786, 0.03439991991523445), (2749, 0.0343974371552427), (1372, 0.034395824258039026), (3240, 0.03439560125943336), (1459, 0.03437967360257597), (612, 0.034347248765360425), (96, 0.034303513993349126), (1002, 0.034288956152525835), (2790, 0.034212880702601825), (1952, 0.03418142615647689), (3188, 0.03413066510207117), (2633, 0.03412171722389169), (1746, 0.034043675089337935), (1021, 0.03399427663562997), (2111, 0.03399039636289066), (256, 0.033985771556006676), (3129, 0.03393622173131106), (572, 0.03392439248161802), (2555, 0.033832402202622854), (1293, 0.033777068901019315), (919, 0.03377378436819052), (1986, 0.03376999463377401), (2760, 0.03366189809586297), (1744, 0.033618627994518036), (3718, 0.033557557152773504), (3653, 0.03354877125343124), (1250, 0.03354850110034634), (71, 0.033508225200710506), (2646, 0.03349697735134021), (505, 0.03349557721464683), (1528, 0.033402622032412635), (1034, 0.033321209434384914), (943, 0.033273809054281844), (512, 0.03322896935558532), (93, 0.03322806248699266), (1137, 0.033159877913394614), (4058, 0.03310569873470425), (2093, 0.03306652573101837), (1462, 0.03305864430749428), (2197, 0.03301962825263696), (304, 0.03294419980174887), (2727, 0.03290660730249757), (4266, 0.03290018056842253), (67, 0.0328333428441088), (1539, 0.032742064428103713), (1756, 0.03268837768695759), (4311, 0.03266929450625021), (1818, 0.032554674906972815), (988, 0.03255230574213255), (2483, 0.03254209118746501), (2406, 0.03253524703425387), (4177, 0.03250422796413294), (4108, 0.03249216018773614), (3590, 0.03241859500129395), (197, 0.032406959125203104), (964, 0.03240173002547836), (1038, 0.03237825755031376), (3289, 0.03236574898053314), (2332, 0.03235837240485982), (3550, 0.03235582356883648), (645, 0.0323495817489502), (3402, 0.032313241299647154), (1477, 0.0322789235976232), (1318, 0.03227141150342942), (372, 0.032226186436677046), (1101, 0.032167601256347704), (2512, 0.03210137538192639), (1690, 0.03209937989015045), (2171, 0.03206368975535113), (268, 0.03205569454885659), (4, 0.03201149009832192), (85, 0.03199890455603978), (1622, 0.031953385230968925), (4166, 0.03193371682236073), (2136, 0.031890114832035174), (2940, 0.031859345900763884), (1516, 0.03183423367870828), (1054, 0.03171382121547129), (1300, 0.03171356662609439), (3864, 0.03170191466554463), (2032, 0.03167817095088653), (2583, 0.03161898672002352), (3293, 0.03161853661045752), (1076, 0.03153288196133954), (1216, 0.03150587977775453), (1104, 0.03150109313522515), (2092, 0.03143859282940303), (4144, 0.03143808202825051), (2796, 0.03143573577872429), (2695, 0.031266849145914204), (3453, 0.03124608204851066), (3853, 0.031210757806299543), (70, 0.03118082314451691), (95, 0.03117009056123546), (1731, 0.031160253338201313), (1631, 0.03112260719543398), (102, 0.03110363302421649), (191, 0.03104622098121053), (2508, 0.03102254363935977), (4265, 0.03096635899455437), (290, 0.030959358960170408), (1453, 0.030951427413894814), (2939, 0.030858756940669252), (3268, 0.030808506929977927), (4324, 0.03076218234981295), (36, 0.03072984932491009), (166, 0.030705845717107036), (828, 0.030602112217709476), (2132, 0.030595066332612983), (4132, 0.030510790929061924), (220, 0.03050440268510147), (2617, 0.030450551286335753), (1352, 0.030444216289263963), (748, 0.030426648527714664), (2698, 0.030423981355135018), (662, 0.0303986442156174), (3636, 0.03038578887124709), (531, 0.030349007889424507), (2098, 0.030340781358753302), (3712, 0.030298996529210136), (502, 0.030291581686212984), (243, 0.030291187951419267), (4257, 0.030286995524668195), (1273, 0.03024051825805572), (2916, 0.03018510076442388), (437, 0.030163104615974035), (4216, 0.030071641939031217), (81, 0.030041188368071327), (2226, 0.030026508233782286), (2289, 0.030003309713059048), (183, 0.029941115802775222), (2400, 0.02988147078939587), (3610, 0.02987789438953137), (91, 0.029807645912977618), (3861, 0.029719305451553796), (2773, 0.0295878814798381), (309, 0.029540393431648774), (2195, 0.02952649908667101), (2216, 0.029526253986259587), (1973, 0.029467101381330837), (1144, 0.02946604107287747), (747, 0.029412591767878467), (4335, 0.029411600402277124), (2575, 0.029403192483548463), (3430, 0.02938367007665103), (3123, 0.029319801746682077), (1196, 0.02929618484408905), (1232, 0.02929551762284517), (1770, 0.029281945747198834), (2746, 0.029251153357369643), (1219, 0.029247920268595195), (3215, 0.0292374726172144), (3337, 0.029199384002199142), (2422, 0.029153233483945398), (1350, 0.029135340315321865), (579, 0.0291303348411868), (203, 0.029097542521276595), (4260, 0.029083240471362758), (2029, 0.02907321649299961), (1537, 0.029071976919342893), (4291, 0.02907115866644311), (3539, 0.029058384252770287), (1988, 0.028960117284703997), (2556, 0.028933720031450234), (2254, 0.028863274499893284), (3599, 0.02881336336558797), (3154, 0.02878492547457735), (129, 0.028773529689352692), (370, 0.028730914433068307), (1877, 0.02869979357915848), (1126, 0.028673423482937856), (864, 0.028669104702679443), (1377, 0.02866907115741002), (2500, 0.028580728452501564), (4029, 0.028564715604642278), (3993, 0.028543155756703836), (2643, 0.028421251601352837), (2310, 0.0283855183151702), (1119, 0.028384316656773784), (3505, 0.028347322644621108), (1594, 0.028323588174158885), (408, 0.028298885130489247), (2325, 0.02816098062395818), (2408, 0.02808872866033859), (3011, 0.028075784694440224), (148, 0.02805477004430571), (3478, 0.028031229739047484), (187, 0.028000396465654144), (3363, 0.02799354335651269), (1135, 0.027990523713294656), (1831, 0.027988579084745394), (3265, 0.027962278008723453), (3259, 0.027957683585766727), (3970, 0.027859465701562815), (550, 0.0278031637234964), (768, 0.02780061397154559), (4211, 0.02779563682419777), (1288, 0.02777606947741958), (3309, 0.027667465886862426), (3839, 0.02766685664109711), (3552, 0.027628827060346063), (2088, 0.02761294518176322), (927, 0.027588870669464853), (3061, 0.027582950477586795), (622, 0.027582472984963545), (219, 0.027578078843797125), (272

In [28]:
top_sim = sort_similar_movies[1:6]
(top_sim)

[(78, 0.45365107541692595),
 (31, 0.37711572930814113),
 (7, 0.26982710977283825),
 (506, 0.2632566436566824),
 (99, 0.23546516195064715)]

In [29]:
# print the name of similar movies based on the index
movie_name = "Iron Man"
print("Movies suggested for you : \n") 
    
i = 1
for movie in top_sim:
        index = movie[0]
        title_movie = data[data.index == index]['title'].values[0]
        print(i , '-' , title_movie)
        i+=1

Movies suggested for you :

1 - Iron Man 2
2 - Iron Man 3
3 - Avengers: Age of Ultron
4 - X-Men
5 - X-Men: First Class

# Full Recommendation System

In [30]:
def recommend_movies(movie_name , cosine_sim = cosine_sim , df = data):
    titles = data['title'].str.lower().tolist()
    movie_name = movie_name.lower()
    
    if movie_name in titles:
        index_of_movie = data[data.title.str.lower() == movie_name].index[0]
        
    else:
        close_match = difflib.get_close_matches(movie_name , titles)
        if not close_match:
            return "Movie not found. Please check the spelling or try another movie."
        index_of_movie = data[data.title.str.lower() == close_match[0]].index[0]
        
    similarity_score = list(enumerate(cosine_sim[index_of_movie]))
    sort_similar_movies = sorted(similarity_score , key = lambda x : x[1] , reverse = True)
    
    top_movies = sort_similar_movies[1:6]
    
    print('Movies suggested for you : \n')
    i = 1
    
    for movie in top_movies:
        index = movie[0]
        title_movie = data[data.index == index]['title'].values[0]
        print(i , '-' , title_movie)
        i+=1

In [32]:
movie_name = "Avatar"
print(f"Recommendations for the Movie")
recommendations = recommend_movies(movie_name)

Recommendations for the Movie
Movies suggested for you :

1 - Lost in Space
2 - Lifeforce
3 - Moonraker
4 - Zathura: A Space Adventure
5 - Space Chimps